server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:26003/railway
    username: postgres
    password: RALdyEHkmyiUQHNxQagXEyVglUIjwJNq
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 57487977584-jdemikeku1330h2kde2ppn30o2foiika.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/calendar
          facebook:
            client-id: 932642091747569
            client-secret: 1c4b4eb92e8251d6ac317f3ddd468d13
            scope:
              - email
              - public_profile